# Generated by Django 2.0.7 on 2018-11-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.CharField(max_length=8)),
                ('full_name', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, max_length=5, null=True)),
                ('email', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'UserBusiness',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.CharField(max_length=8, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'GroupBusiness',
                'db_table': 'GroupBusiness',
            },
        ),
    ]
