# Generated by Django 2.0.7 on 2018-11-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_auto_20181109_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbusiness',
            options={'verbose_name_plural': 'UserBusiness'},
        ),
    ]
