# Generated by Django 2.0.7 on 2018-11-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0003_auto_20181109_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbusiness',
            options={'managed': True, 'verbose_name_plural': 'UserBusiness'},
        ),
    ]
