# Generated by Django 2.0.7 on 2018-11-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_auto_20181114_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbusiness',
            options={'verbose_name_plural': 'UserBusiness'},
        ),
    ]
