# Generated by Django 2.1.3 on 2018-11-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_auto_20181114_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupbusiness',
            options={'verbose_name_plural': 'groupbusiness'},
        ),
        migrations.AlterModelOptions(
            name='userbusiness',
            options={'verbose_name_plural': 'userbusiness'},
        ),
        migrations.AddField(
            model_name='groupbusiness',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='groupbusiness',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='groupbusiness',
            name='pulau',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='wilayah',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='groupbusiness',
            name='is_active',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='groupbusiness',
            name='tipe_sistem',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userbusiness',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbusiness',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userbusiness',
            name='role',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userbusiness',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelTable(
            name='groupbusiness',
            table='groupbusiness',
        ),
        migrations.AlterModelTable(
            name='userbusiness',
            table='userbusiness',
        ),
    ]
